name: wisemonster
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.1+29

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_settings: 4.1.8
  http: ^0.13.1
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.9
  uuid: 3.0.5
  flutter_web_auth: ^0.5.0
  image_picker: ^0.8.4+11
  multiple_images_picker: ^1.0.1
  connectivity_plus: ^2.3.6
  permission_handler: ^10.0.2
  table_calendar: ^3.0.7
  contacts_service: ^0.6.3
  firebase_messaging: ^14.0.2
  flutter_local_notifications: ^9.2.0
  agora_rtc_engine: ^6.0.0
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  firebase_in_app_messaging: ^0.7.0+2
  qr_code_scanner: ^1.0.1
  flutter_blue_plus: ^1.3.1
  encrypt: ^5.0.1
  byte_util: ^1.1.3
  hex: ^0.2.0
  intl: ^0.17.0
  grouped_list: ^5.1.2
  flutter_phoenix: ^1.0.0
  settings_ui: ^2.0.2
  mqtt_client: ^9.7.2
  video_player: ^2.4.8
  camera: ^0.10.0+4
  path_provider: ^2.0.11
  network_info_plus: ^3.0.1
  device_info_plus: ^8.0.0
  quiver: ^3.1.0
  cryptography: ^2.0.5
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - images/default/
    - images/icon/

